tables:
  - "^COM"
  - "^COB"
  - "DDM_CLASS"
  - "DDM_SUBCLASS"
  - "DDM_LIMITEDWORD"
  - "DDM_SIMPLELW"
  - "MSM_AGCONTENT"
  - "MSM_ATTRIBUTE"
  - "MSM_ATTRIBUTEGROUP"
  - "MSM_CATALOGCLASS"
  - "MSM_CATALOGINTERFACE"
  - "MSM_CCCONTENT"
  - "SPM_FILETYPE"
  - "SPM_FILE"
  - "SPM_STORAGEAREA"
  - "SPM_STORAGEPATH"